### ISSUE TITLE
How can I search historical anything?

### ISSUE THREAD

**Issue by furkankaradas** [djkelleher/search-engines#7]
Hi,

Thank you for this library, it is amazing! I want to access historical news yahoo or google. How can I do this with these library?

Thank you.

**Comment by djkelleher** [comment]
Thanks, glad you like it! 

You can follow the `next_page_url`s in a loop (I just added an example at the bottom of the README). News search results are usually time-ordered, so pages further back will be older/more historical. If you want older than what is currently available from the search engines, then I would look into internet archives (not supported by this package) like [Common Crawl](https://commoncrawl.org/) and Wayback Machine(https://archive.org/web/)

**Comment by furkankaradas** [comment]
Thank you for helping!
